#if !canImport(ObjectiveC)
import XCTest

extension FileUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileUtilsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FileUtilsTests.__allTests__FileUtilsTests),
    ]
}
#endif
